### ISSUE TITLE
Add Röti station

### ISSUE THREAD

**Issue by McRender** [ysavary/WindMobile2-Server#26]
Hi there

The crew from the DCW (dcweissenstein.ch) have just mounted a new weather station on top of the Röti of the Weissenstein in Switzerland. Would you be so kind and add it to winds.mobi? You can find the data at http://holfuy.com/en/data/507.

Kind Regards
Stephan

**Comment by ysavary** [comment]
Hi Stephan,

Holfuy-507 is now available here: https://winds.mobi/stations/map/holfuy-507

Yann

**Comment by McRender** [comment]
Hi Yann

Thank you very much for adding the new station to winds.mobi
This is a great add-on for all local pilots :-)

Stephan

**Comment by McRender** [comment]
Hi Yann 

We had to replace our station on the Röti. The URL changed therefore as well: https://holfuy.com/en/data/1368
Do you mind updating the provider for winds.mobi?

Kind Regards,
Stephan
