### ISSUE TITLE
Login with Google is broken

### ISSUE THREAD

**Issue by mkeller** [ysavary/WindMobile2-Server#30]
For quite a while now, the login / save favorites feature is broken. The "Sign in with Google" button points to https://winds.mobi/auth/google/oauth2callback/ , but that link returns a 404.

Same problem with the Facebook login page, but that doesn't bother me too much ;-)

**Comment by mkeller** [comment]
Works again.

**Comment by ysavary** [comment]
Hi Markus,

I'm sorry, I tried to respond to every people that contacted me about the issue with social logins but i forgot this message. Happy that it works for you again!

By the way, the new repositories are here: https://github.com/winds-mobi/

Yann
